local addonName, addon = ...
Guidelime.registerGuide([[
[D*MarkyMark*'s 1-60 guide\\https://www.twitch.tv/darealmarkymark\\(best suited for a group of at least 2, if not 3+)]
[GA Alliance]
[N29-30 Ashenvale]
[NX30-31 Wetlands]
Fly to [F Astranaar]
Accept [QA4581 Kayneth Stillwind]
Accept [QA1022 The Howling Vale] & [QA1021 Vile Satyr! Dryads in Danger]!
Accept [QA1035 Fallen Sky Lake]
Do [QC1035 Fallen Sky Lake]
Turn in [QT4581 Kayneth Stillwind]
Accept [QA1011 Forsaken Diseases]
Go to Satyrnaar and free the soul there for [QC1140,2 The Tower of Althalaxx Part 7] - Click on the glowing circle [G82,49Ashenvale]
Turn in [QT1021 Vile Satyr! Dryads in Danger!], accept [QA1031 The Branch of Cenarius] [G78,45Ashenvale]
Kill [QC1031,1 Geltharis] nearby for [QC1031 The Branch of Cenarius] [G78,42Ashenvale]
Clear southwest to Night Run and free the soul there for [QC1140,1 The Tower of Althalaxx Part 7] [G67,57Ashenvale]
Grind to [G54,35Ashenvale] and loot the Warn Chest for [QC1026 Raene's Cleansing] - Make sure to have Wooden Key from Crazed/Withered Ancients [G54.6, 35.4Ashenvale]
Run up the hill to the Worgen cave and read from the [QC1022,1 Tome of Mel'Thandris] on the table [G51,39Ashenvale]
Grind to Shael'dryn at the Moonwell (Entrance at [G50,50Ashenvale]) and turn in [QT1026 Raene's Cleansing Part 4], accept [QA1027 Part 5] [G53.5, 46.2Ashenvale]
Grind down to[OC] [G75,71Ashenvale] and kill oozes in the area - loot the chest for [QC1027 Raene's Cleansing Part 5]
Do [QC1011 Forsaken Diseases]
Turn in [QT1027 Raene's Cleansing Part 5], accept [QA1028 Part 6]
Go to [G55,51Ashenvale] and run up the moutain, click the stone to turn in [QT1028 Raene's Cleansing Part 6], accept [QA1055 Part 7]
Turn in [QT1055 Raene's Cleansing Part 7], accept [QA1029 Part 8]
Turn in [QT1011 Forsaken Diseases] & accept [QA1012 Insane Druids]
Run east to Azshara and get the [P]FP, fly to [F Astranaar]
Turn in [QT1022 The Howling Vale], accept [QA1037 Velinde Starsong]
Turn in [QT1031 The Branch of Cenarius], accept [QA1032 Satyr Slaying!]
Turn in [QT1140 The Tower of Althalaxx Part 7], skip the [QS1167 next part]
Turn in [QT1029 Raene's Cleansing Part 8], accept [QA1030 Part 9]
Turn in [QT1035 Fallen Sky Lake]
If you're level [XP 30] or 31 already, you can skip the next parts all the way down to the 'Fly to [F Darnassus]' step if you choose to
Run south to [G51,75Ashenvale] and use the Rod to speak to Krolg and turn in [QT1030 Raene's Cleansing Part 9], accept [QA1045 Part 10] [G51,75Ashenvale]
Do [QC1045 Raene's Cleansing Part 10] [G55,80Ashenvale]
Turn in [QT1045 Raene's Cleansing Part 10], accept [QA1046 Part 11] - Abandon this portion if you want to save your Furbolg Rod
Do [QC1012 Insane Druids] - pathing: https://classicdb.ch/?quest=1012
Run north to Satyrnaar and do [QC1032 Satyr Slaying!] [G80,51Ashenvale]
Turn in [QT1012 Insane Druids]
Run to[OC] Azshara and fly to [F Astranaar]
Turn in [QT1046 Raene's Cleansing Part 11] if you don't care to keep the Furbolg Rod
Turn in [QT1032 Satyr Slaying!]
Fly to [F Darnassus]
Turn in [QT1037 Velinde Starsong] [G62,39Ashenvale]
Accept [QA1038 Velinde's Effects]
Do [QC1038 Velinde's Effects] at [G62,83Ashenvale] in Darnassus [G62,83Ashenvale]
Turn in [QT1038 Velinde's Effects]
Accept [QA1039 The Barrens Port]
Check the Auction House for Swiftness Potions, [V buy] 5 each if possible & 1x Swim Speed Potion each
Hearth to [H Wetlands]
]],'MarkyMark')