local addonName, addon = ...
Guidelime.registerGuide([[
[D*MarkyMark*'s 1-60 guide\\https://www.twitch.tv/darealmarkymark\\(best suited for a group of at least 2, if not 3+)]
[GA Alliance]
[N27-30 Duskwood/Stockades]
[NX29-30 Ashenvale]
Accept [QA66 The Legend of Stalvan], [QA149 Ghost Hair Thread] and [QA101 The Totem of Infliction]
Set your Hearth to [S Darkshire]
Accept [QA56 The Night Watch]
Turn in [QT66 The Legend of Stalvan], accept [QA67 Part 2]
Accept [QA173 Worgen in the Woods]
Accept [QA174 Look to the Stars]
Turn in [QT174 Look to the Stars], accept [QA175 Part 2]
Turn in [QT149 Ghost Hair Thread] & [QT175 Look to the Stars Part 2]
Accept [QA154 Return the Comb] & [QA177 Look to the Stars Part 3]
Go south to the chapel and do [QC177 Look to the Stars Part 3] & [QC56 The Night Watch]
Turn in [QT177 Look to the Stars Part 3], accept [QA181 Part 4]
Turn in [QT154 Return the Comb], accept [QA157 Deliver the Thread]
Turn in [QT56 The Night Watch], accept [QA57 Part 2]
Go west to the Rotting Orchard at [G62,62Duskwood] and do [QC173 Worgen in the Woods]
Turn in [QT95 Sven's Revenge] [G50,78Duskwood]
Accept [QA230 Sven's Camp]
Turn in [QT157 Deliver the Thread]
Accept [QA158 Zombie Juice] [G28, 31Duskwood]
Accept [QA225 The Weathered Grave] [G18,29Duskwood]
Turn in [QT230 Sven's Camp] [G8,33Duskwood]
Accept [QA262 The Shadowy Figure]
Run west into westfall and go to the Moonbrook Schoolhouse [G42,67Duskwood]
Turn in [QT67 The Legend of Stalvan Part 2], accept [QA68 Part 3]
Hearth to [H Darkshire]
Turn in [QT158 Zombie Juice], accept [QA156 Gather Rot Blossoms]
Run north to manor mistmantle and loot Tear of Tilloa for [QC335 A Noble Brew] [G77,36Duskwood]
Turn in [QT68 The Legend of Stalvan Part 3], accept [QA69 Part 4]
Turn in [QT225 The Weathered Grave], accept [QA227 Morgan Ladimore]
Turn in [QT227 Morgan Ladimore], accept [QA228 Mor'Ladim]
Turn in [QT173 Worgen in the Woods Part 1], accept [QA221 Part 2]
Turn in [QT262 The Shadowy Figure], accept [QA265 The Shadowy Search Continues]
Turn in [QT265 The Shadowy Search Continues], accept [QA266 Inquire at the Inn]
Turn in [QT266 Inquire at the Inn], accept [QA453 Finding the Shadowy Figure]
Go west to the Rotting Orchard and do [QC221 Worgen in the Woods Part 2]
Turn in [QT453 Finding the Shadowy Figure], accept [QA268 Return to Sven]
Do [QC156 Gather Rot Blossoms] and [QC57 The Night Watch Part 2]
Do [QC228 Mor'Ladim]
Turn in [QT268 Return to Sven], accept [QA323 Proving your Worth]
At the Tower of Azora in Elwynn, turn in [QT249 Morganth] & [QT178 Theocritus' Retrieval]
Do [QC69 The Legend of Stalvan Part 4], accept [QA70 Part 5] at the Goldshire Inn
Run north to Stormwind, turn in [QT335 A Noble Brew], accept [QA336 Part 2] [G26,79Duskwood]
Turn in [QT70 The Legend of Stalvan Part 5] [G30,62Duskwood]
Accept [QA72 The Legend of Stalvan Part 6]
Turn in [QT72 The Legend of Stalvan Part 6], accept [QA74 Part 7]
Accept [QA343 Speaking of Fortitude] at the Cathedral [G46,38Duskwood]
Accept [QA1274 The Missing Diplomat] inside the Cathedral
Turn in [QT336 A Noble Brew]
Turn in [QT1274 The Missing Diplomat] inside Stormwind Keep at [G78,25Duskwood] & accept [QA1241 Part 2]
Turn in [QT337 An Old History Book], accept [QA538 Southshore] at [G74,7Duskwood] inside Stormwind Keep
Turn in [QT343 Speaking of Fortitude], skip the [QS344 next part]
Turn in [QT1241 The Missing Diplomat Part 2] in The Valley of Heroes, accept [QA1242 Part 3]
Turn in [QT1242 The Missing Diplomat Part 3] in The Trade District, accept [QA1243 Part 4]
Fly to [F Redridge]
Run west to Elwynn and go to Eastvale Logging Camp
Turn in [QT74 The Legend of Stalvan Part 7], accept [QA75 Part 8] [G84.5, 69.4Duskwood]
Do [QC75 The Legend of Stalvan Part 8] - Loot the chest upstairs and turn [QT75 it] in
Accept [QA78 The Legend of Stalvan Part 9]
Run south into Duskwood along the road and find Watcher Backus
Turn in [QT1243 The Missing Diplomat Part 4], accept [QA1244 Part 5]
Turn in [QT78 The Legend of Stalvan Part 9] & [QT156 Gather Rot Blossoms]
Accept [QA79 The Legend of Stalvan Part 10] & [QA159 Juice Delivery]
Turn in [QT79 The Legend of Stalvan Part 10],  accept [QA80 Part 11]
Turn in [QT80 The Legend of Stalvan Part 11], accept [QA97 Part 12]
Turn in [QT97 The Legend of Stalvan Part 12], accept [QA98 Part 13]
Turn in [QT57 The Night Watch Part 2], accept [QA58 Part 3]
Turn in [QT228 Mor'Ladim], accept [QA229 The Daughter Who Lived]
Turn in [QT229 The Daughter Who Lived] & accept [QA231 A Daughter's Love]
Turn in [QT221 Worgen in the Woods Part 2], accept [QA222 Part 3]
Fly to [F Westfall] [G18,29Duskwood]
Turn in [QT231 A Daughter's Love]
Turn in [QT159 Juice Delivery]
Accept [QA133 Ghoulish Effigy]
Go into the crypt and do [QC133 Ghoulish Effigy], [QC58 The Night Watch Part 3] & [QC101 The Totem of Infliction]
Turn in [QT133 Ghoulish Effigy]
Accept [QA134 Ogre Thieves]
Go to the western crypt and do [QC323 Proving your Worth]
Turn in [QT323 Proving your Worth]
Accept [QA269 Seeking Wisdom]
Run south Addle's Stead and get the [QC1244,1 Defias Docket] in the strongbox for [QC1244 The Missing Diplomat]
Do [QC134 Ogre Thieves] and [QC181 Look to The Stars] [G24.3, 71.3Duskwood]
Turn in [QT134 Ogre Thieves], accept [QA160 Note to the Mayor]
Hearth to [H Darkshire]
Turn in [QT58 The Night Watch Part 3]
Turn in [QT160 Note to the Mayor], accept [QA251 Translate Abercrombie's Note]
Turn in [QT251 Translate Abercrombie's Note], accept [QA401 Wait for Sirra to Finish]
Turn in [QT401 Wait for Sirra to Finish], accept [QA252 Translation to Ello]
Turn in [QT252 Translation to Ello]
Accept [QA253 Bride of the Embalmer]
Turn in [QT101 The Totem of Infliction]
Turn in [QT181 Look to the Stars]
Do [QC98 The Legend of Stalvan Part 13] [G77,36Duskwood]
Turn in [QT1244 The Missing Diplomat Part 5], accept [QA1245 Part 6]
Turn in [QT98 The Legend of Stalvan Part 13]
Accept [QA377 Crime and Punishment] if you didn't do Stockades already
Fly to [F Stormwind]
Turn in [QT1245 The Missing Diplomat Part 6], accept [QA1246 Part 7]
Turn in [QT1246 The Missing Diplomat Part 7], accept [QA1447 Part 8] and fight the NPCs
Turn in [QT1447 The Missing Diplomat Part 8], accept [QA1247 Part 9]
Accept [QA388 The Color of Blood]
Turn in [QT1247 The Missing Diplomat Part 9], accept [QA1248 Part 10]
Turn in [QT269 Seeking Wisdom], accept [QA270 The Doomed Fleet]
Accept [QA387 Quell the Uprising] if you didn't do Stockades already
Do The Stockades if you haven't already
Once done, turn in [QT387 Quell the Uprising]
Accept [QA690 Malin's Request] - *Requires Level [XP 30]*
Get Elixir of Water Breathing out of the bank
Turn in [QT388 The Color of Blood]
Turn in [QT386 What Comes Around...]
Turn in [QT377 Crime and Punishment]
Fly to [F Menethil] Harbor
Set hearth to [S Wetlands]
Turn in [QT1248 The Missing Diplomat Part 10], accept [QA1249 Part 11]
Subdue Tapoke 'Slim' Jahn and turn in [QT1249 Part 11], accept [QA1250 Part 12]
Turn in [QT270 The Doomed Fleet], accept [QA321 Lightforge Iron]
Take the boat to Darkshore
]],'MarkyMark')