local addonName, addon = ...
Guidelime.registerGuide([[
[D*MarkyMark*'s 1-60 guide\\https://www.twitch.tv/darealmarkymark\\(best suited for a group of at least 2, if not 3+)]
[GA Alliance]
[N16-18 Loch Modan]
[NX18-20 Redridge]
Set Hearth in [S Thelsamar]
Accept [QA436 Ironband's Excavation]
Do [QC237 In Defense of the King's Lands Part 2]
Turn in [QT237 In Defense of the King's Lands Part 2]
Accept [QA263 In Defense of the King's Lands Part 3]
Turn in [QT436 Ironband's Excavation], accept [QA297 Gathering Idols]
Accept [QA298 Excavation Progress Report]
[V Buy] Solstice Robe and Wise Man's Belt from [V vendor] (Caster only)
Do [QC297 Gathering Idols]
Turn in [QT297 Gathering Idols]
Accept [QA257 A Hunter's Boast]
Accept [QA385 Crocolisk Hunting]
Do [QC257 A Hunter's Boast]
Turn in [QT257 A Hunter's Boast], accept [QA258 A Hunter's Challenge]
Do [QC258 A Hunter's Challenge]
Turn in [QT258 A Hunter's Challenge], accept [QA271 Vyrin's Revenge]
Turn in [QT2039 Find Bingles], accept [QA2038 Bingles' Missing Supplies]
Do [QC385 Crocolisk Hunting]
Do [QC2038 Bingles' Missing Supplies] & [QC263 In Defense of the King's Lands Part 3]
Accept [QA250 A Dark Threat Looms]
Turn in [QT250 A Dark Threat Looms], accept [QA199 Part 2] [G56,13Loch Modan]
Turn in [QT199 A Dark Threat Looms Part 2], accept [QA161 A Dark Threat Looms Part 3]
Hearth to [H Thelsamar]
Accpet and turn in [QT418 Thelsamar Blood Sausages] if you have the items for it from grinding around Loch Modan
Turn in [QT298 Excavation Progress Report], accept [QA301 Report to Ironforge]
Turn in [QT263 In Defense of the King's Lands Part 3]
Accept [QA217 In Defense of the King's Lands Part 4]
Do [QC217 In Defense of the King's Lands Part 4]
Turn in [QT217 In Defense of the King's Lands Part 4]
Do [QC271 Vyrin's Revenge]
Turn in [QT2038 Bingles' Missing Supplies]
Turn in [QT385 Crocolisk Hunting] & [QT271 Vyrin's Revenge]
Accept [QA531 Vyrin's Revenge Part 2]
Turn in [QT531 Vyrin's Revenge Part 2]
Use auto-unstuck, spirit res in Thelsamar
Fly to [F Ironforge]
Turn in [QT301 Report to Ironforge]
Accept [QA2041 Speak with Shoni]
Take the tram to Stormwind
Accept [QA6661 Deeprun Rat Roundup]
Do [QC6661 Deeprun Rat Roundup]
Turn in [QT6661 Deeprun Rat Roundup], skip the [QS6662 next part]
Turn in [QT2041 Speak with Shoni], accept [QA2040 Underground Assault]
Turn in [QT1338 Stormpike's Order]
Accept [QA167 Oh Brother...]
Accept [QA168 Collecting Memories]
Accept [QA2281 Redridge Rendezvous][A Rogue] [A Rogue]
[T Train] class abilities, INCLUDING LOCKPICKING AND [V BUY] THIEVES TOOLS. LEVEL COOKING TO 50
[V Buy] Stormwind Seasoning Herbs [G61,61Loch Modan]
Accept [QA3765 The Corruption Abroad] - If you aren't level [XP 18] to pick this up, there is another chance to do so later [G21,56Loch Modan]
Fly to [F Westfall]
Accept [QA65 The Defias Brotherhood Part 1]
Fly to [F Stormwind]
Run to[OC] Goldshire
Set your Hearth in [S Goldshire]
Run to[OC] Redridge
]],'MarkyMark')