local addonName, addon = ...
Guidelime.registerGuide([[
[D*MarkyMark*'s 1-60 guide\\https://www.twitch.tv/darealmarkymark\\(best suited for a group of at least 2, if not 3+)]
[GA Alliance]
[N18-20 Redridge]
[NX20-21 Duskwood]
Accept [QA244 Encroaching Gnolls] [G15,71Redridge Mountains]
Turn in [QT244 Encroaching Gnolls]
Accept [QA246 Assessing the Threat] [G30.8,60.1Redridge Mountains]
Accept [QA125 The Lost Tools]
Accept [QA118 The Price of Shoes]
Accept [QA120 Messenger to Stormwind]
Accept [QA127 Selling Fish]
Go in the inn, accept [QA129 A Free Lunch]
Turn in [QT65 The Defias Brotherhood Part 1], accept [QA132 Part 2]
Walk up the hill, accept [QA92 Redridge Goulash]
Hearth to [H Goldshire]
Turn in [QT118 The Price of Shoes], accept [QA119 Return to Verner] [G37.8, 54.4Redridge Mountains]
Turn in [QT120 Messenger to Stormwind] [G41.4, 54.9Redridge Mountains]
Accept [QA121 Messenger to Stormwind Part 2]
Fly to [F Westfall]
Turn in [QT132 The Defias Brotherhood Part 2], accept [QA135 Part 3]
Fly to [F Stormwind]
Turn in [QT135 The Defias Brotherhood Part 3], accept [QA141 Part 4]
Fly to [F Westall]
Turn in [QT141 The Defias Brotherhood Part 4], accept [QA142 Part 5]
Do [QC142 The Defias Brotherhood Part 5] 
**ESCORT NEXT STEP**
Turn in [QT142 The Defias Brotherhood Part 5]
Accept [QA155 The Defias Brotherhood Part 6] (Escort)
Turn in [QT155 The Defias Brotherhood Part 6], accept [QA166 Part 7]
Accept [QA214 Red Silk Bandanas]
You can do The Deadmines now or after Redridge or Duskwood - Set your Hearth to [H Westfall] if you're doing it now
Fly to [F Redridge]
Turn in [QT119 Return to Verner], accept [QA122 Underbelly Scales] & [QA124 A Baying of Gnolls] [G15,71Redridge Mountains]
Turn in [QT121 Messenger to Stormwind Part 2], skip the [QS145 next part]
Accept [QA3741 Hilary's Necklace]
Turn in [QT2281 Redridge Rendezvous][A Rogue], accept [QA2282 Alther's Mill][A Rogue] [A Rogue]
Do [QC3741 Hilary's Necklace]
Do [QC125 The Lost Tools] [G42,55Redridge Mountains]
Do [QC127 Selling Fish] at the southern Murloc camp as well as collect 8 Murloc Fins (DON'T SELL)
Do [QC246 Assessing the Threat]
Turn in [QT129 A Free Lunch], accept [QA130 Visit the Herbalist]
Turn in [QT246 Assessing the Threat]
Accept [QA20 Blackrock Menace]
Turn in [QT125 The Lost Tools], accept [QA89 The Everstill Bridge]
Turn in [QT127 Selling Fish]
Turn in [QT130 Visit the Herbalist], accept [QA131 Delivering Daffodils]
Turn in [QT131 Delivering Daffodils]
Turn in [QT3741 Hilary's Necklace]
Do [QC124 A Baying of Gnolls], [QC89 The Everstill Bridge], [QC20 Blackrock Menace] & [QC122 Underbelly Scales] north of Lakeshire
Do [QC92 Redridge Goulash] at Alther's Mill
Do [QC2282 Alther's Mill][A Rogue] [A Rogue]
Turn in [QT20 Blackrock Menace]
Turn in [QT89 The Everstill Bridge] & [QT122 Underbelly Scales]
Turn in [QT124 A Baying of Gnolls], skip the [QS126 next part] for now
Turn in [QT2282 Alther's Mill][A Rogue] [A Rogue]
Turn in [QT92 Redridge Goulash]
Accept [QA34 An Unwelcome Guest]
Do [QC34 An Unwelcome Guest]
Turn in [QT34 An Unwelcome Guest]
Do The Deadmines now or after Duskwood
Turn in [QT166 The Defias Brotherhood Part 7]
Turn in [QT214 Red Silk Bandanas]
Fly to [F Redridge]
]],'MarkyMark')