local addonName, addon = ...
Guidelime.registerGuide([[
[D*MarkyMark*'s 1-60 guide\\https://www.twitch.tv/darealmarkymark\\(best suited for a group of at least 2, if not 3+)]
[GA Alliance]
[N42-44 STV]
[NX44-45 Tanaris]
Set your Hearth to [H Booty] Bay 
Accept [QA600 Venture Company Mining] & [QA621 Zanzil's Secret]
Turn in [QT603 Ansirem's Key], accept [QA610 'Pretty Boy' Duncan]
Turn in [QT669 Sunken Treasure Part 4], accept [QA670 Part 5]
Accept [QA209 Skullsplitter Tusks]
Accept [QA627 Favor For Krazek] and turn [QT627 it] in if the AH had Bloodstone Ore, accept the [QA622 next part]
Accept [QA617 Akiris By The Bundle]
Accept [QA606 Scaring Shaky]
Accept [QA348 Stranglethorn Fever]
Accept [QA595 The Bloodsail Buccaneers]
Accept [QA628 Excelsior]
Turn in [QT595 The Bloodsail Buccaneers], accept [QA597 Part 2] & do "[QC610 'Pretty Boy' Duncan]
Do [QC617 Akiris By The Bundle]
At the top of the hill, across the bridge - loot the 'Holy Spring Water' from the Holy Spring for [QC48 Sweet Amber]
Do [QC606 Scaring Shaky]
Collect 10 [QC349,1 Gorilla Fangs] then run up to the cave and do [QC348 Stranglethorn Fever]
Turn in [QT606 Scaring Shaky], accept [QA607 Return to MacKinley]
Turn in [QT348 Stranglethorn Fever]
Turn in [QT607 Return to MacKinley], accept [QA609 Voodoo Dues]
Turn in [QT617 Akiris By The Bundle], accept [QA623 Part 2]
Turn in [QT610 'Pretty Boy' Duncan], accept [QA611 The Curse of the Tides]
Turn in [QT597 The Bloodsail Buccaneers Part 2], accept [QA599 Part 3]
Turn in [QT599 The Bloodsail Buccaneers Part 3], accept [QA604 Part 4] 
Accept [QA587 Up To Snuff]
Accept [QA576 Keep An Eye Out]
Do [QC1119 Zanzil's Mixture and a Fool's Stout] & [QC609 Voodoo Dues]
Do [QC197 Raptor Mastery Part 4] (Tethis)
Do [QC600 Venture Company Mining]
Finish [QC192 Panther Mastery Part 3]
Do [QC209 Skullsplitter Tusks] & [QC205 Troll Witchery]
Turn in [QT197 Raptor Mastery] & [QT192 Panther Mastery], accept [QA193 Panther Mastery Part 4]
Turn in [QT205 Troll Witchery], accept [QA206 Mai'Zoth]
Hearth to [H Booty] Bay
Turn in [QT621 Zanzil's Secret] & [QT600 Venture Company Mining]
Turn in [QT209 Skullsplitter Tusks]
Turn in [QT609 Voodoo Dues], accept [QA613 Cracking Maury's Foot]
Do [QC604 The Bloodsail Buccaneers Part 4], [QC587 Up To Snuff] & [QC576 Keep An Eye Out]
While here, keep an eye out for the [QA594 Message in a Bottle] [OC]
Do [QC206 Mai'Zoth] & [QC613 Cracking Maury's Foot]
Do [QC193 Panther Mastery Part 4]
Turn in [QT206 Mai'Zoth]
Turn in [QT193 Panther Mastery], accept [QA208 Big Game Hunter]
Do [QC208 Big Game Hunter]
Run west to the coast and kill an [QC628,1 Elder Saltwater Crocolisk] for [QC628 Excelsior]
Do [QC611 The Curse of the Tides]
Swim north to Westfall and turn in [QT48 Sweet Amber], accept [QA49 Part 2] [G45,80 Westfall]
Hearth to [H Booty] Bay if it's up, if not run to[OC] Sentinel Hill and [F]fly
Turn in [QT587 Up To Snuff]
Turn in [QT611 The Curse of the Tides]
Turn in [QT604 The Bloodsail Buccaneers Part 4], accept [QA608 Part 5]
Accept [QA1117 Rumors for Kravel], [QA1183 Goblin Sponsorship] & [QA2864 Tran'rek]
Turn in [QT613 Cracking Maury's Foot], accept [QA2872 Stoley's Debt]
Turn in [QT628 Excelsior]
Turn in [QT576 Keep An Eye Out]
Swim out to the island with the statue, kill Mok'rash and loot the belt, accept [QA8552 The Monogrammed Sash]
Turn in [QT8552 The Monogrammed Sash], accept [QA615 The Captain's Cutlass]
Turn in [QT615 The Captain's Cutlass], skip the [QS618 next part] for now
Do [QC608 The Bloodsail Buccaneers Part 5]
Keep an eye out for [QA624 Cortello's Riddle] and loot it while on the boats, accept [QA624 Cortello's Riddle]
If it wasn't up earlier, Hearth to [H Booty] Bay otherwise run back
Turn in [QT608 The Bloodsail Buccaneers Part 5]
Take the boat to Ratchet
Fly to [F Theramore]
Turn in [QT623 Akiris By The Bundle Part 2]
Do level 40 First Aid quest if you've leveled it
Fly to [F Gadgetzan]
]],'MarkyMark')