local addonName, addon = ...
Guidelime.registerGuide([[
[D*MarkyMark*'s 1-60 guide\\https://www.twitch.tv/darealmarkymark\\(best suited for a group of at least 2, if not 3+)]
[GA Alliance]
[N47-49 Tanaris/ZF]
[NX49-50 Searing Gorge]
Fly to [F Theramore]
Swim across Dustwallow to [G55,51Tanaris] (Entrance to land from water) quest items are at [G54,55Tanaris] and loot the 'Overdue Package' for [QC4450 Ledger from Tanaris]
Loot the 'Seaforium Booster' nearby for [QC1187 Razzeric's Tweaking]
Accept [QA2846 Tiara of the Deep] [G46,57Tanaris]
Turn in [QT625 Cortello's Riddle Part 2], accept [QA626 Part 3] [G31,66Tanaris]
Fly to [F Gadgetzan]
Turn in [QT1119 Zanzil's Mixture and a Fool's Stout] if you did it, accept [QA1121 Get the Goblin's Drunk]
Turn in [QT1121 Get the Goblin's Drunk]
Go back to Kravel and accept [QA1122 Report Back to Fizzlebub]
Turn in [QT1187 Razzeric's Tweaking], accept [QA1188 Safety First]
Accept [QA2770 Gahz'rilla]
Turn in [QT1188 Safety First], accept [QA1189 Part 2]
Accept [QA82 Noxious Lair Investigation]
Accept [QA3362 Thistleshrub Valley]
Accept [QA5863 The Dunemaul Compound]
Accept [QA2605 The Thirsty Goblin]
Turn in [QT4450 Ledger From Tanaris]
Turn in [QT3445 The Sunken Temple], accept [QA3161 Gahz'ridian] - Skip [QS3444 The Stone Circle] for now
Do [QC82 Noxious Lair Investigation]
Do [QC5863 The Dunemaul Compound]
Do [QC3161 Gahz'ridian]
Turn in [QT2946 Seeing What Happens] [G38,81Tanaris]
Accept [QA2954 The Stone Watcher]
Turn in [QT2954 The Stone Watcher], accept [QA2977 Return to Ironforge]
Do [QC3362 Thistleshrub Valley] & [QC2605 The Thirsty Goblin]
**ESCORTS NEXT TWO STEPS**
Accept [QA1560 Tooga's Quest] (Escort) [G32,74Tanaris]
Run east and turn in [QT351 Find OOX-17/TN], accept [QA648 Rescue OOX-17/TN!] (Escort)
Turn in [QT1560 Tooga's Quest] [G67,26Tanaris]
Turn in [QT3520 Screecher Spirits], accept [QA3527 The Prophecy of Mosh'aru]
Turn in [QT3161 Gahzridian], accept [QA3444 The Stone Circle]
Turn in [QT82 Noxious Lair Investigation], accept [QA10 The Scrimshank Redemption]
Turn in [QT5863 The Dunemaul Compound]
Turn in [QT3362 Thistleshrub Valley]
Turn in [QT2605 The Thirsty Goblin], accept [QA2606 In Good Taste]
Turn in [QT2606 In Good Taste], accept [QA2641 Sprinkle's Secret Ingredient]
Set your Hearth to [H Gadgetzan]
Run south to the hive entrance at [G56,70Tanaris] and take the first entrance on the left and follow it through - at the fork, take a left
In the big room with the 4 corners, the Surveying Gear is directly on your left when you walk in for [QC10 The Scrimshank Redemption]
Hearth to [H Gadgetzan]
Turn in [QT10 The Scrimshank Redemption], accept [QA110 Insect Part Analysis]
Turn in [QT110 Insect Part Analysis], accept [QA113 Part 2]
Turn in [QT113 Insect Part Analysis Part 2], accept [QA162 Rise of the Silithid]
Accept [QA2865 Scarab Shells]
Accept [QA3042 Troll Temper]
Accept [QA2768 Divino-matic Rod]
**Do Zul'Farrak**
Hearth to [H Gadgetzan] if it's up, if not then run back
Turn in [QT2865 Scarab Shells]
Turn in [QT3042 Troll Temper]
Turn in [QT2768 Divino-matic Rod]
Turn in [QT2770 Gahz'rilla]
Turn in [QT1189 Safety First Part 2]
Turn in [QT3527 The Prophecy of Mosh'aru], accept [QA4787 The Ancient Egg]
Run all the way down to Un'goro Crater
Accept [QA4289 The Apes of Un'goro] [G72,76Tanaris]
Accept [QA3844 It's a Secret to Everybody] from 'A Wrecked Raft' [G63,69Tanaris]
Turn in [QT3844 It's a Secret to Everybody] at 'A Small Pack' under the water, accept [QA3845 Part 2]
Turn in [QT3845 It's a Secret to Everybody Part 2], accept [QA3908 Part 3]
Get the [P]FP
Fly to [F Dustwallow] Marsh
Turn in [QT2846 Tiara of the Deep]
Auto unstuck and spirit res in Theramore
Fly to [F Ratchet]
Take the boat to Booty Bay
Turn in [QT648 Rescue OOX-17/TN!], accept [QA3721 An OOX of Your Own]
Turn in [QT3721 An OOX of Your Own]
Turn in [QT1122 Report Back to Fizzlebub]
Fly to [F Ironforge]
]],'MarkyMark')